SELECT DISTINCT F.CATEGORY, MP.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT F, (
        SELECT MAX(PRICE) AS MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY
    ) MP
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
AND F.PRICE = MP.MAX_PRICE
ORDER BY MAX_PRICE DESC;