-- SELECT
SELECT F.FLAVOR
FROM FIRST_HALF F, JULY J
WHERE F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
LIMIT 3;

-- 서브쿼리 이용
SELECT FLAVOR
FROM (
    SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS STO 
    FROM FIRST_HALF F, JULY J
    WHERE F.FLAVOR = J.FLAVOR
    GROUP BY FLAVOR
    ORDER BY STO DESC 
    LIMIT 3
) A;